[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "osqp"
dynamic = ["version"]
description = "OSQP: The Operator Splitting QP Solver"
readme = "README.rst"
requires-python = ">=3.7"
authors = [
    { name = "Bartolomeo Stellato", email = "bartolomeo.stellato@gmail.com" },
    { name = "Goran Banjac" },
]
dependencies = [
    "jinja2",
    "numpy>=1.7",
    "qdldl",
    "scipy>=0.13.2",
    "setuptools",
]

[project.optional-dependencies]
cuda = [
    "osqp-cuda",
]
dev = [
    "numdifftools",
    "pre-commit",
    "pytest>=6",
    "torch",
]
mkl = [
    "osqp-mkl",
]

[project.urls]
Homepage = "https://osqp.org/"


[tool.scikit-build]
install.components = ["python", "codegen"]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
minimum-version = "0.8"


[[tool.scikit-build.generate]]
path = "osqp/_version.py"
template = '''
version = __version__ = "${version}"
'''

[tool.scikit-build.cmake.define]
OSQP_ALGEBRA_BACKEND = "builtin"
OSQP_EXT_MODULE_NAME = "ext_builtin"

[tool.pytest.ini_options]
testpaths = ["src/osqp/tests"]

[tool.setuptools_scm]
