name: Build Default

on:
  push:
    branches: [ master, develop* ]
    tags:
      - '*'
  pull_request:
    branches: [ master, develop* ]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022]

    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      if: startsWith(matrix.os, 'windows')

    - name: Add Windows SDK
      shell: cmd
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install windows-sdk-8.1

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.9'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.2
      with:
        output-dir: wheelhouse
      env:
        CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux_*"
        CIBW_BEFORE_TEST: pip3 install pytest numdifftools && pip3 install torch --index-url https://download.pytorch.org/whl/nightly/cpu
        CIBW_TEST_COMMAND: "python -m pytest -s {project}/src/osqp/tests"

    - name: Build source
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        python -m pip install --upgrade build
        python -m build --sdist --outdir wheelhouse

    - name: Release to pypi
      # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      if: ${{ false }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY: testpypi
      run: |
        python -m pip install --upgrade twine
        twine upload wheelhouse/*

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
